[package]
name = "tdengine-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/refe[http]

[dependencies]
iced = "0.9"
iced_aw = { version = "0.5", default-features = false, features = ["icons"] }
anyhow = "*"
mysql = "*"

